import numpy as np
a=[float(i) for i in input().split()]
l1=np.array(a)
print(l1)
b=tuple([float(i) for i in input().split()])
t1=np.array(b)
print(t1)
l3=np.zeros((3,4))
print(l3)
l4=np.arange(0,25,5)
print(l4)
l5=np.reshape(l3,(2,2,3))
print(l5)
l6 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Rowwise min: ",np.min(l6,0))
print("Rowwise max: ",np.max(l6,0))
print("colwise min: ",np.min(l6,1))
print("colwise max: ",np.max(l6,1))
print("SUm of elements: ",np.sum(l6))